# Generated by Django 4.1.6 on 2023-02-08 05:12

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ady')),
            ],
            options={
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ady')),
            ],
            options={
                'verbose_name_plural': 'Taglar',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ady')),
                ('text', ckeditor.fields.RichTextField(verbose_name='text')),
                ('image', models.ImageField(upload_to='postImage/', verbose_name='surat')),
                ('seen', models.PositiveIntegerField(verbose_name='görülen sany')),
                ('hot', models.PositiveIntegerField(verbose_name='gyzgynlygy')),
                ('share', models.PositiveIntegerField(verbose_name='paýlaşylan sany')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='goşulan güni')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.category', verbose_name='category')),
                ('like', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='like sany')),
                ('tagList', models.ManyToManyField(to='posts.tag', verbose_name='taglar')),
            ],
            options={
                'verbose_name_plural': 'Makalalar',
            },
        ),
    ]
