# Generated by Django 4.1.6 on 2023-02-08 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_remove_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-createdAt',), 'verbose_name_plural': 'Makalalar'},
        ),
        migrations.AlterField(
            model_name='post',
            name='hot',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='gyzgynlygy'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='like sany'),
        ),
        migrations.AlterField(
            model_name='post',
            name='seen',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='görülen sany'),
        ),
        migrations.AlterField(
            model_name='post',
            name='share',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='paýlaşylan sany'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tagList',
            field=models.ManyToManyField(related_query_name='tags', to='posts.tag', verbose_name='taglar'),
        ),
    ]
