# Generated by Django 4.1.6 on 2023-02-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_options_alter_post_hot_alter_post_like_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='ady')),
            ],
            options={
                'verbose_name_plural': 'Ulanyjylar',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
