# Generated by Django 4.1.6 on 2023-02-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_hot_alter_post_seen_alter_post_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hot',
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, to='posts.userid', verbose_name='like sany'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='seen',
        ),
        migrations.AddField(
            model_name='post',
            name='seen',
            field=models.ManyToManyField(blank=True, related_name='gorulen', to='posts.userid', verbose_name='görülen sany'),
        ),
    ]
