# Generated by Django 4.1.6 on 2023-02-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_hot_alter_post_like_remove_post_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tagList',
            field=models.ManyToManyField(related_query_name='tagList', to='posts.tag', verbose_name='taglar'),
        ),
    ]
