# Generated by Django 4.1.6 on 2023-02-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_hot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hot',
        ),
    ]
