# Generated by Django 4.1.6 on 2023-02-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_category_alter_post_options_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blurHash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='blurhash'),
        ),
    ]
