# Generated by Django 4.1.6 on 2023-02-23 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0014_alter_userinterests_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='like sany'),
        ),
        migrations.AlterField(
            model_name='post',
            name='seen',
            field=models.ManyToManyField(blank=True, related_name='gorulen', to=settings.AUTH_USER_MODEL, verbose_name='görülen sany'),
        ),
    ]
