# Generated by Django 4.1.6 on 2023-02-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_delete_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterests',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.category', verbose_name='category'),
        ),
    ]
